#!/usr/bin/env node
/**
 * scripts/record-session.js
 *
 * Generate / refresh `docs/terminal-demo.svg` - the animated terminal
 * "demo" used at the top of README.md. We deliberately do NOT shell out
 * to a GIF recorder (no ffmpeg, no asciinema, no node-pty dependency)
 * because the readme has to render on every platform GitHub supports.
 *
 * The output is pure SVG with `<animate>` keyframes, so it works inline
 * on github.com, in NPM's package readme renderer, and as a static OG
 * preview when downscaled.
 *
 * Usage:
 *   node scripts/record-session.js              # rewrite docs/terminal-demo.svg
 *   node scripts/record-session.js --check      # exit 1 if the file is stale
 *
 * The "session" content is defined in `SCENES` below. Edit those four
 * scenes to update the demo.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const SCENES = [
  // [keyTimesIn, keyTimesOut] are positions inside a 12-second loop.
  {
    in:  0.04, out: 0.30,
    lines: [
      ['#7afcb1', '$ npx terminal-quest-cli'],
      ['#a5b3cf', '[boot] kimi-os v2.5.0  loading filesystem ......... ok'],
      ['#a5b3cf', '[boot] mounting /world  /shadow  /system .......... ok'],
      ['#a5b3cf', '[boot] hydrating quest pack (2 community) ......... ok'],
      ['#ffd866', '  Welcome, explorer. The terminal remembers you.'],
      ['#7d8597', '  Lv.4  -  18 achievements  -  alignment +2  -  04:12'],
      ['#ff79c6', '[Lv.4] explorer@kimi-os:~$']
    ]
  },
  {
    in:  0.34, out: 0.55,
    lines: [
      ['#ff79c6', '[Lv.4] explorer@kimi-os:~$ ls'],
      ['#7afcb1', 'diary.txt   notes.md   start_here.txt   .secret/'],
      ['#ff79c6', '[Lv.4] explorer@kimi-os:~$ cd /world/lab'],
      ['#a5b3cf', 'You step into the abandoned research lab. The fan hums.'],
      ['#a5b3cf', 'A figure in a soldering apron looks up. "You again."'],
      ['#ffd866', '  +25 EXP (visited /world/lab)']
    ]
  },
  {
    in:  0.59, out: 0.80,
    lines: [
      ['#ff79c6', '[Lv.4] explorer@kimi-os:/world/lab$ talk engineer'],
      ['#a5b3cf', 'Engineer: "Take this. The cipher is old, but the message is not."'],
      ['#7afcb1', '  -> received: cipher.enc'],
      ['#ff79c6', '[Lv.4] explorer@kimi-os:/world/lab$ decode cipher.enc'],
      ['#ffd866', '  decoded: "the master key is hidden where the night never ends"'],
      ['#7afcb1', '  [achievement] Cryptographer  (+50 EXP)']
    ]
  },
  {
    in:  0.84, out: 1.00,
    lines: [
      ['#ff79c6', '[Lv.4] explorer@kimi-os:/world/lab$ run cipher'],
      ['#a5b3cf', '  scrambled: "WKLV LV ZKHQ"  shift = ?'],
      ['#fefefe', '  > 3'],
      ['#7afcb1', '  match looks like English  (+30 EXP)'],
      ['#ffd866', '  *** LEVEL UP ***   Lv.5  Shadow Walker'],
      ['#a5b3cf', '  Unlocked area: /shadow/realm/']
    ]
  }
];

const DUR = '12s';
const W = 820;
const H = 460;

function escape(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderScene(scene, idx) {
  const lines = scene.lines.map((l, i) => {
    const y = 60 + i * 26;
    return `    <text x="20" y="${y}" fill="${l[0]}">${escape(l[1])}</text>`;
  }).join('\n');
  // 4-keyframe envelope: hidden -> hidden -> visible -> hidden
  const k = `${scene.in - 0.001};${scene.in};${scene.out - 0.04};${scene.out}`
    .split(';').map((s) => Math.max(0, Math.min(1, parseFloat(s))).toFixed(4)).join(';');
  return `  <g opacity="0">
    <animate attributeName="opacity" values="0;1;1;0" keyTimes="${k}" dur="${DUR}" repeatCount="indefinite"/>
${lines}
  </g>`;
}

function buildSvg() {
  const scenes = SCENES.map(renderScene).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by scripts/record-session.js - edit SCENES there, then re-run. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" font-family="ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace" font-size="14">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#1b1f2a"/>
      <stop offset="100%" stop-color="#10131a"/>
    </linearGradient>
  </defs>
  <rect x="0" y="0" width="${W}" height="${H}" rx="10" ry="10" fill="url(#bg)"/>
  <rect x="0" y="0" width="${W}" height="28" rx="10" ry="10" fill="#262a36"/>
  <rect x="0" y="20" width="${W}" height="10" fill="#262a36"/>
  <circle cx="16" cy="14" r="6" fill="#ff5f56"/>
  <circle cx="36" cy="14" r="6" fill="#ffbd2e"/>
  <circle cx="56" cy="14" r="6" fill="#27c93f"/>
  <text x="${W / 2}" y="18" fill="#7d8597" text-anchor="middle" font-size="11">terminal-quest-cli  -  npx terminal-quest-cli</text>
${scenes}
  <text x="${W / 2}" y="${H - 22}" fill="#5a637a" text-anchor="middle" font-size="11">npx terminal-quest-cli  -  bilingual RPG, multi-slot saves, community quests, cloud sync</text>
</svg>
`;
}

function main() {
  const out = path.join(__dirname, '..', 'docs', 'terminal-demo.svg');
  const svg = buildSvg();
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(out)) {
      console.error('docs/terminal-demo.svg is missing - run scripts/record-session.js');
      process.exit(1);
    }
    const cur = fs.readFileSync(out, 'utf8');
    if (cur.trim() !== svg.trim()) {
      console.error('docs/terminal-demo.svg is stale - re-run scripts/record-session.js');
      process.exit(1);
    }
    console.log('docs/terminal-demo.svg up to date');
    return;
  }
  fs.writeFileSync(out, svg);
  console.log(`wrote ${out} (${Buffer.byteLength(svg)} bytes, ${SCENES.length} scenes)`);
}

main();
